#!/bin/sh

#XDG stuff, cuz lightdm is a pain
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"

export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

export WINEPREFIX="$XDG_DATA_HOME"/wine
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=${XDG_CONFIG_HOME}/java -Djavafx.cachedir=${XDG_CACHE_HOME}/openjfx"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export DISTCC_DIR="$XDG_CONFIG_HOME"/distcc
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export HISTFILE="${XDG_STATE_HOME}"/bash/history

#The actual bspwm stuff
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

bspc monitor DisplayPort-0 -d u q
bspc monitor DisplayPort-1 -d i w
bspc monitor DisplayPort-2 -d o e 
bspc monitor HDMI-A-0 -d      p r

feh --bg-fill $HOME/Pictures/Wallpapers/19.jpg

bspc config border_width         1
bspc config window_gap           7

bspc config focus_follows_pointer        true
#bspc config pointer_follows_focus        true
bspc config pointer_follows_monitor      true
bspc config -m DisplayPort-2 top_padding 26

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Xfdesktop:xfdesktop:Desktop focus=off follow=off
bspc rule -a Xfce4-panel:xfce4-panel:* state=floating
bspc rule -a *:*:Application\ Finder state=floating follow=on
bspc rule -a com-atlauncher-App desktop='o' state=floating
bspc rule -a *:*:ATLauncher\ Console desktop='u' state=pseudo_tiled
bspc rule -a mxie.exe state=tiled
bspc rule -a *:*:MXIE\ User\ Login state=floating
bspc rule -a *:*:3140\ role state=floating
bspc rule -a screenconnect.windowsclient.exe:screenconnect.windowsclient.exe:* desktop='w' state=pseudo_tiled
bspc rule -a screenconnect.windowsclient.exe:screenconnect.windowsclient.exe:ScreenConnect\ -\ Exit\ Application state=floating
